Feature: Validating the Creation and Formatting of the JSON generated

  Scenario: 02-0001 Transform Valid Dataset in JSON
      Given I have a Dataset
      When I validate the Dataset with a base json
      Then I see that the two are compatible
  
  Scenario Outline: 02-0002 Return Invalid Path on Wrong Path structure
      Given I have a Dataset with <invalid_path>
      When I validate the Dataset with wrong path
      Then I see message of invalid path

   Examples: Invalid Paths
    | invalid_path  | 
    |//Test@Test    |
    |/Test/!Test    |
    |\Test\Test     |
    |Test/Test      |
    |/Test/Test./   |
    |/Test\Test     |
    |\Test/Test     |
    |Test           |

  Scenario Outline: 02-0003 Return Obligatory Field $Name_of_field Not Found if dataset gives insufficient minimal data
      Given I have a Dataset generated by the WebScraper with "<vendor>","<url>","<series>","<category>","<model>","<path>","<release>"
      When I validate the Dataset with wrong field
      Then I see message with invalid <field>
  
   Examples: Empty Fields
    | vendor  | url                                                                           | series                            | category  | model                     | path                                                               | release  | field   |
    | null    |https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|vendor   |
    |cisco.com| null                                                                          |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|url      |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |   null                            |Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|series   |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|   null    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|category |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |   null                    |/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|model    |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|  null                                                              |1404766800|path     |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|   null   |release  |