Feature: Validating the Creation and Formatting of the JSON generated

  Scenario: 02-0001 Transform Valid Dataset in JSON
      Given I have a Dataset
      When I validate the Dataset with a base json
      Then I see that the two are compatible
  
  Scenario Outline: 02-0002 Return Invalid Path on Wrong Path structure
      Given I have a Dataset with <invalid_path>
      When I validate the Dataset with wrong path
      Then I see message of invalid path

   Examples: Invalid Paths
    | invalid_path  | 
    |//Test/Test    |
    |/Test//Test    |
    |\Test\Test     |
    |Test/Test      |
    |/Test/Test//   |
    |/Test\Test     |
    |\Test/Test     |
    |Test           |

  Scenario Outline: 02-0003 Return Obligatory Field $Name_of_field Not Found if dataset gives insufficient minimal data
      Given I have a Dataset generated by the WebScraper with <vendor>,<url>,<series>,<category>,<model>,<path>,<release>
      When I validate the Dataset with wrong field
      Then I see message of invalid <field>
  
   Examples: Invalid Paths
    | vendor  | url                                                                           | series                            | category  | model                     | path                                                               | release  | field   |
    |         |https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|Vendor   |
    |cisco.com|                                                                               |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|URL      |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |                                   |Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|Series   |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|           |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|Category |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |                           |/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|1404766800|Model    |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|                                                                    |1404766800|Path     |
    |cisco.com|https://www.cisco.com/c/en/us/support/routers/910-industrial-router/model.html |Cisco 900 Series Industrial Routers|Routers    |Cisco 910 Industrial Router|/Support/Product Support/Routers/Cisco 900 Series Industrial Routers|          |Release  |